name: Check OSM Versions

on:
  pull_request:
    branches: [ master ]

jobs:
  osm-versions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Verify that OSMs have been updated
      shell: bash
      run: |
          ruby ./developer/ruby/CheckOSMVersions.rb

    - name: Suggest correcting steps
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "There is a workflow called export_standards_data that you should run first (it's a manual workflow_dispatch workflow)"
        echo "or run it locally via 'cd developer/ruby && openstudio export_openstudio_standards_libraries.rb'"
        echo ""
        echo "Then you should use 'openstudio developer/ruby/UpdateOSMVersions.rb' to version translate the rest of the OSM files."
